# Generated by Django 4.2.7 on 2024-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
