# Generated by Django 4.2.7 on 2023-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_record_attribute_record_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='количество Дизлайков'),
        ),
        migrations.AlterField(
            model_name='record',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='количесвто Лайков'),
        ),
    ]
