# Generated by Django 4.2.7 on 2023-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_record_dislikes_count_alter_record_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='publicated',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
