# Generated by Django 4.2.7 on 2024-02-13 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_version_v_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('v_name',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AddField(
            model_name='version',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
