# Generated by Django 4.2.7 on 2024-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publicated',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
